//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.ViewerJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_home_facility
    {
        public int F_id { get; set; }
        public string House_type { get; set; }
        public int House_area { get; set; }
        public int House_total_area { get; set; }
        public string roof_type { get; set; }
        public Nullable<bool> on_rent { get; set; }
        public string cooking_type { get; set; }
        public string entertainment { get; set; }
        public int annual_income { get; set; }
        public string drinking_water_TYPE { get; set; }
        public string irrigation_type { get; set; }
        public string ownership_type { get; set; }
        public int storey { get; set; }
        public Nullable<bool> electricity { get; set; }
        public Nullable<int> senior_id { get; set; }
    
        public virtual table_house_senior_details table_house_senior_details { get; set; }
    }
}
