//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anupasthit_bekti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anupasthit_bekti()
        {
            this.anupasthit_bekti_many = new HashSet<anupasthit_bekti_many>();
        }
    
        public int AB_ID { get; set; }
        public Nullable<int> senior_id { get; set; }
    
        public virtual table_house_senior_details table_house_senior_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anupasthit_bekti_many> anupasthit_bekti_many { get; set; }
    }
}
