//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apangata
    {
        public int apangaID { get; set; }
        public Nullable<bool> apangata1 { get; set; }
        public string apanga_type { get; set; }
        public Nullable<int> senior_id { get; set; }
    
        public virtual table_house_senior_details table_house_senior_details { get; set; }
    }
}
