//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pariwar_bekti_bibarand_many
    {
        public int PBM_ID { get; set; }
        public string Name { get; set; }
        public string nata { get; set; }
        public string gender { get; set; }
        public string birth_place { get; set; }
        public string education { get; set; }
        public Nullable<int> age { get; set; }
        public string age_group { get; set; }
        public Nullable<int> PB_ID { get; set; }
    
        public virtual pariwar_bekti_bibarand pariwar_bekti_bibarand { get; set; }
    }
}
