//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_home_facilities
    {
        public int id { get; set; }
        public int Home_no { get; set; }
        public string House_type { get; set; }
        public int House_area { get; set; }
        public int House_total_area { get; set; }
        public string roof_type { get; set; }
        public bool on_rent { get; set; }
        public string cooking_type { get; set; }
        public string Entertainment { get; set; }
        public int Annual_income { get; set; }
        public string Drinking_water_type { get; set; }
        public string Irrigation_type { get; set; }
        public string road_type { get; set; }
        public string ownership_type { get; set; }
        public int storey { get; set; }
        public bool electricity { get; set; }
    
        public virtual table_address table_address { get; set; }
        public virtual table_demographic table_demographic { get; set; }
        public virtual table_house_senior_detail table_house_senior_detail { get; set; }
    }
}
