//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_house_senior_detail
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Home_no { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public int Contact_no { get; set; }
        public System.DateTime DOB { get; set; }
        public string Birth_place { get; set; }
        public string Citizenship_no { get; set; }
        public System.DateTime Citizenship_Issue_date { get; set; }
        public string Citizenship_issue_district { get; set; }
    
        public virtual table_home_facilities table_home_facilities { get; set; }
    }
}
