//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woda_test.Models
{
    using Models;
    using System;
    using System.Collections.Generic;

    public partial class table_house_senior_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_house_senior_details()
        {
            this.table_address = new HashSet<table_address>();
            this.table_demographic = new HashSet<table_demographic>();
            this.table_home_facility = new HashSet<table_home_facility>();
        }
    
        public int senior_id { get; set; }
       
        public int Home_no { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public int Contact_no { get; set; }
        public System.DateTime DOB { get; set; }
        public string BirthPlace { get; set; }
        public string CitizenShip_no { get; set; }
        public string CitizenshipIssue_district { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_address> table_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_demographic> table_demographic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_home_facility> table_home_facility { get; set; }
    }
}
